---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "duck-back-service"
  namespace: "default"
  labels:
    app: "duck-back"
spec:
  ports:
  - protocol: "TCP"
    port: 8080
    targetPort: 8080
  selector:
    app: "duck-back"
  type: "ClusterIP"
