apiVersion: v1
kind: Service
metadata:
  name: duck-front-service
spec:
  selector:
    app: duck-front
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  clusterIP: 10.0.3.204
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.70.236.154